services:
  backend:
    container_name: lateralthinking-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/lateralthinking/backend
    ports:
      - "8001:8001"
    env_file:
      - ./backend/var.env
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - lateralthinking-network
    command: bash ./setup.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 20s

  frontend:
    container_name: lateralthinking-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/lateralthinking/frontend
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    command: npm run start
    
    networks:
      - lateralthinking-network

  mongo:
    container_name: lateralthinking-mongo
    image: mongo:7.0
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - lateralthinking-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 10s


networks:
  lateralthinking-network:

volumes:
  mongodata:
    driver: local
